<a href="https://colab.research.google.com/github/Andrea227/dailyexercise/blob/master/Home_Assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Question 1

In [0]:
import numpy as np
from numpy.linalg import eig

In [0]:
w, v = eig(np.array([[10, 4], [4, 2]]))

In [0]:
print(w)

[11.65685425  0.34314575]


In [0]:
print(v)

[[ 0.92387953 -0.38268343]
 [ 0.38268343  0.92387953]]


In [0]:
v1 = np.matrix.transpose(v)
print(v1)

[[ 0.92387953  0.38268343]
 [-0.38268343  0.92387953]]


In [0]:
v*v1

array([[ 0.85355339, -0.14644661],
       [-0.14644661,  0.85355339]])

In [0]:
Sw = np.array([[14/9, 4/9],[4/9, 2/9]])
Sw

array([[1.55555556, 0.44444444],
       [0.44444444, 0.22222222]])

In [0]:
Sw2 = np.linalg.inv(Sw)
Sw2

array([[ 1.5, -3. ],
       [-3. , 10.5]])

![微信图片_20200428041638.jpg](https://i.loli.net/2020/04/28/y8F7kvM13QgUbeD.jpg)
![微信图片_20200428041645.jpg](https://i.loli.net/2020/04/28/8UI3WHigS2Pqmyn.jpg)

E) The reason that LDA will not give the principal component with greatest variation is because the LDA intends to maximize the component axes for class-separation, maximize between the class but minimize in the class, which is supervised; while, PCA tries to find the component that maximize the variance among all the data points.

# 2. Question 2

PCA may not preserve the pairwise distance between every pair of the data points as perfectly as MDS does. Since MDS intends to preserve and reconstruct the relationships of positions in the lower dimesnsions, and if we are using Sammon mapping then it will accurate for the data points which have smaller distances. What Dr.Smart would like to do by using PCA will only preserve large distances of data points since PCA will discard the dimension which has relatively small variance. It will leads to some sort of distorting of the pairwise distances even if the effect may be small.

However, this might not be always true. If we are considering using Euclidean space for inputs of MDS, the MDS inputs matrix of distance could be transformed to get the position input matrix that PCA uses. And then we could use the seperation of eigenvalues and pick the top n large corresponding eigenvactors. MDS will be equivalent to PCA under this circumstance since they are both doing eigenvalue seperations.

# 3. Question 3

In [0]:
from sklearn.cluster import KMeans
X = np.array([[1, 1], [1.5, 2], [3, 4],
             [5, 7], [3.5, 5], [4.5, 5], [3.5, 4.5]])
km = KMeans(n_clusters=2, init = np.array([[1,1],[5,7]]), verbose=1, max_iter=1)

In [0]:
ykm = km.fit(X)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 12.208333333333334


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  """Entry point for launching an IPython kernel.


In [0]:
ykm.cluster_centers_

array([[1.83333333, 2.33333333],
       [4.125     , 5.375     ]])

In [0]:
ykm.labels_

array([0, 0, 1, 1, 1, 1, 1], dtype=int32)

In [0]:
km = KMeans(n_clusters=2, init = np.array([[1,1],[5,7]]),verbose=1, max_iter=2)
ykm = km.fit(X)
ykm.cluster_centers_

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 12.208333333333334
start iteration
done sorting
end inner loop
Iteration 1, inertia 8.525


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  


array([[1.25, 1.5 ],
       [3.9 , 5.1 ]])

In [0]:
ykm.labels_

array([0, 0, 1, 1, 1, 1, 1], dtype=int32)

In [0]:
km = KMeans(n_clusters=2, init = np.array([[1,1],[5,7]]),verbose=1, max_iter=3)
ykm = km.fit(X)
ykm.cluster_centers_

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 12.208333333333334
start iteration
done sorting
end inner loop
Iteration 1, inertia 8.525
start iteration
done sorting
end inner loop
Iteration 2, inertia 8.525
center shift 0.000000e+00 within tolerance 2.647959e-04


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  


array([[1.25, 1.5 ],
       [3.9 , 5.1 ]])

In [0]:
ykm.labels_

array([0, 0, 1, 1, 1, 1, 1], dtype=int32)

In [0]:
km = KMeans(n_clusters=2, init = np.array([[1,1],[5,7]]),verbose=1, max_iter=4)
ykm = km.fit(X)
ykm.cluster_centers_

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 12.208333333333334
start iteration
done sorting
end inner loop
Iteration 1, inertia 8.525
start iteration
done sorting
end inner loop
Iteration 2, inertia 8.525
center shift 0.000000e+00 within tolerance 2.647959e-04


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  


array([[1.25, 1.5 ],
       [3.9 , 5.1 ]])

In [0]:
ykm.labels_

array([0, 0, 1, 1, 1, 1, 1], dtype=int32)

![微信图片_20200428070338.jpg](https://i.loli.net/2020/04/28/z36SgcQ1lyiPG8m.jpg)

# 4. Question 4

The input variables are: (i) the time of day they log in, (ii) the length of time they log in for, (iii) the types of programs they run while logged in, (iv) the number of programs they run while logged in.

When the intruder logged on, these four feartures will somehow honestly portrait unusal activities. So it is possible that we could have 2 clusters, on e for normal circumstances and the other for unusual intruder activties. Hence the topology preservation could learn when shows intruder coming in.

I think since all four variables have different measurements, we may need to normalize the inputs before training. Since activities may vary either normal or unusual in different time of the day, the data should be in a form that activties/time or time/activities.

The data size needs to be calculated. We may first tested with different size and make some subtle changes. And then we could decided the number of neurons and the number of weights. Since we may change the data form into two dimensions, it's possible that could build a two-dimension network.

It could work to test intruder, however, we may add some other algorithm to help it learn to tell normal noises and real unusual class.



# 5. Question 5

I think this system might work. However, due to the complexity and a huge amount of the input data, it might be overfitting and has slow speed if we do not preprocess the data to align their forms to a simpler form like their final outputs, stolen or not stolen.

We could simply take the two stolen feautures as a binary option: 1 for stolen, 0 or empty for not been stoled or not transactions on stolen cards. And then we could balance and normalize the data.

In this case, I may recommend using K-means data that it could learn how to cluster the data into normal and fraudulent classes.